version: "3"
services:
  # 1 key per container you want to run
  web:
    build: . # location of dockerfile
    ports:
      - "8080:8080"
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

volumes:
  db-data:
